### ISSUE TITLE
Not working when device language is not English.

### ISSUE THREAD

**Issue by alex-crr** [fischman/NoExplore#1]
I don't really know how to describe this, the app just doesn't really do anything. I'm on a xiaomi 11 lite 5g ne, running miui global 14.0.2. I installed the app, gave it the accessibility permissions. I rebooted my phone, launched instagram but the explore button, as well as the reels button still works. My guess is that, since the app is a service, I need to somehow start it? Any help would be greatly appreciated @fischman

**Comment by fischman** [comment]
You shouldn't need to start the app explicitly. Registering as a service and allowing the permission effectively has it running permanently in the background. What version of Android are you on? I've only tested on 14 but could try an older version if needed.
Oh also the app keys off specific text strings that the Instagram app uses, which I guess could be different in different languages (I've only tested in US/English). What language does Instagram talk to you in?

(Also, thanks for trying the app and reporting this issue! You might be only the second person to try the app besides me 🤣)

**Comment by alex-crr** [comment]
miui 14 should be based on android 14, but I'll check. I'm using Instagram in French, and I'm trying it in English right now.

**Comment by alex-crr** [comment]
Heck yeah it works. I'll check out if there's any way to autodetect language and send the string in the correct language. Thank you so much for this awesome project, I've been wanting something like that for a long time. I will try to share this as much as I can, and update you if ever I find a bug

**Comment by fischman** [comment]
Should be fixed in https://github.com/fischman/NoExplore/releases/v0.3
Thanks again for the report!
