### ISSUE TITLE
Suggested posts up-scroll only works if there is some feed content (to avoid app becoming unusable when there is no friend content)

### ISSUE THREAD

**Issue by alex-crr** [fischman/NoExplore#2]
Back at it, the 0.3 release seems to not feature the scrollup function when reaching the `Suggestes Posts` in the home-feed, however it was working in 0.2. Is it a bug or a feature?

**Comment by fischman** [comment]
It should still work.
Note that it only triggers if the suggested posts header is near the bottom
of the screen (top >1000 dp, which on your phone should be ~42% from the
top) to avoid infinite loops if you don't have any friends contents to see.
But also that height restriction hasn't changed from 0.2 to 0.3. but ofc if
you had friend content to see when testing 0.2 and not when testing 0.3
that would account for the difference.

Are you set up to build the app from source or are you willing to try test
builds if I add some debugging code to try and figure this out?

**Comment by alex-crr** [comment]
That's probably it. However that means it's a possible bypass of the lock. I'm currently not equipped to build from source, but I'll take some time in the near future to try and do it myself. I can also try test builds if that helps you. I also found a way to bypass the lock on the `Explore` page, but I'm not sure if anything can be done to stop it, as it's directly due to Instagram' mechanic and the way the service processes.

**Comment by fischman** [comment]
Yeah, it's not hermetic...
I was just thinking yesterday of maybe trying a notification or alarm or
something if it notices you've bypassed in a way that it was unable to
prevent.
(Ideal would be to paint over the UI with an obscuring element but that
would require _another_ scary permission 🤣. Might try it anyway)

**Comment by alex-crr** [comment]
I'm curious on how you know when you've entered an element. Does it sends a signal saying you've moved there, or can you detect the state of the app?

**Comment by fischman** [comment]
> I'm curious on how you know when you've entered an element

The app registers an AccessibilityService that gets [notified](https://github.com/fischman/NoExplore/blob/bbe731b8f551152dfb30f937949487d73d621619/app/src/main/java/org/fischman/noexplore/NoExploreService.java#L56) when various UI events happen, including TYPE_WINDOW_CONTENT_CHANGED and TYPE_VIEW_SELECTED. Suggested Posts is detected via its [container](https://github.com/fischman/NoExplore/blob/bbe731b8f551152dfb30f937949487d73d621619/app/src/main/java/org/fischman/noexplore/NoExploreService.java#L139).

**Comment by fischman** [comment]
The real reason I suppress the UP action when there is no new feed content is to enable watching friends' stories.
Maybe the suppression should conditionalize on the presence of unwatched stories...

**Comment by alex-crr** [comment]
Thanks for the explanations. I think this issue is more of a `feature-request`/`improvement` type.

**Comment by fischman** [comment]
> Ideal would be to paint over the UI with an obscuring element

Figured out a way to do this without an extra scary permission.
Try out https://github.com/fischman/NoExplore/releases/tag/v0.4 and LMK how it feels?
