### ISSUE TITLE
"This service does not work" error in `Àccesibility settings`

### ISSUE THREAD

**Issue by alex-crr** [fischman/NoExplore#3]
Sometimes the service doesn't work. After a quick check in the `Accessibility Settings` it reveals that the service is still "On", but isn't working. It has happened quite a few times and usually turning t off and back on seems to resolve the problem. I'll include some photos, and try to see if I can find a way to obtain logs.![Screenshot_2023-11-27-06-47-21-992_com.android.settings.jpg](https://github.com/fischman/NoExplore/assets/73464112/29ff09c6-d22e-4c1d-8d59-d68eb4282de2)

![Screenshot_2023-11-27-06-47-25-268_com.android.settings.jpg](https://github.com/fischman/NoExplore/assets/73464112/cdc5ebc8-fba1-4ae3-96a2-2e87bba168e4)

**Comment by fischman** [comment]
Hmm, I've not seen these errors. 

Looks like the error you get when a [service is enabled but also has crashed](https://android.googlesource.com/platform/packages/apps/Settings/+/master/src/com/android/settings/accessibility/AccessibilitySettings.java#252). 

> try to see if I can find a way to obtain logs.

If you can build the app yourself, then flipping [DEBUG](https://github.com/fischman/NoExplore/blob/bbe731b8f551152dfb30f937949487d73d621619/app/src/main/java/org/fischman/noexplore/NoExploreService.java#L15) to true should yield useful logs in `adb logcat`.

**Comment by fischman** [comment]
(in fact, I'm guessing the error you're seeing is due to a service crash, so even without flipping DEBUG logcat will likely contain a backtrace that may be informative)

**Comment by alex-crr** [comment]
I seem to have figured out the pattern. When my phone is in sleep mode, and Instagram is left running, the service seems to stop working (as in, it does not behave like it's supposed to, but no actual crash, no settings error) but closing and reopening the app seems to solve that problem. However if this cycle is repeated, the service ends up definitely crashing.

**Comment by fischman** [comment]
Any exceptions in the logs?

**Comment by alex-crr** [comment]
I'm facing some difficulties accessing the logcat, I'll have to try and look up how to do it the smart way :)

**Comment by fischman** [comment]
> but closing and reopening the app seems to solve that problem.

Does a tiny scroll make the obscuring work again? A shortcoming of the existing implementation is that the screen's contents are only evaluated when they change, and coming back from sleep doesn't count as a "change" AFAICT.
