### ISSUE TITLE
Reduce min-sdk runtime requirement

### ISSUE THREAD

**Issue by Vorlod-exe** [fischman/NoExplore#5]
This public interest application should be accessible to as many people as possible! (Thank you very much)

The current minimum requirement is Android 13, but this application could only reach 22% of devices according to Android Studio. With a few modifications, it is at least possible to lower this requirement to Android 11, which would allow it to reach 59% of devices.

**Comment by Vorlod-exe** [comment]
PS: I am creating a stable branch that addresses this issue.

**Comment by fischman** [comment]
@Vorlod-exe have you already created a patch that implements this?

I originally went with SDK version 34 for simplicity (to avoid compatibility shims that I didn't need for my own device). I'm happy to lower this as far as is practical/useful where it comes it little/no cost.
What SDK version is your device running?

**Comment by fischman** [comment]
Released in https://github.com/fischman/DisableDistractions/releases/tag/v0.8

**Comment by Vorlod-exe** [comment]
Yes, I have a few stable codes where, in addition to modifying the manifest, I have:
1. Replaced `getBoundsInWindow` with `getBoundsInScreen` as the former is not compatible with my SDK.
2. Not using an overlay but implemented a `GLOBAL_ACTION_BACK` because:
     - Managing the overlay can lead to service interruptions in some cases.
     - A too fast scroll makes the overlay disappear.

The only issue with the second point is that occasionally, Instagram starts by displaying the tag on the home screen, and the application closes in this case. I'm currently pondering a way to resolve it.

In any case, as it stands, the new release is not compatible with the desired versions, including my SDK level 30.

**Comment by fischman** [comment]
> The only issue with the second point is that occasionally, Instagram starts by displaying the tag on the home screen, and the application closes in this case. I'm currently pondering a way to resolve it.

FYI the code prior to https://github.com/fischman/DisableDistractions/commit/bceae468aa0df51901d81661f5b788568c972184 had some workarounds for this, but they were not particularly robust.

Not sure why Android Studio didn't flag that getBoundsInWindow requires API 34. Will take a whack at replacing that as #6.
